name: Build and test solution
on:
  pull_request:
    types: [opened, reopened, synchronize]

  # Allows to be called by another workflow
  workflow_call:
    secrets:
      NEXT_URL:
        description: 'Next URL.'
        default: 'http://localhost:3000'
      WORDPRESS_PATH:
        required: true
        description: 'WordPress absolute path on remote server.'
      WORDPRESS_URL:
        description: 'WordPress URL'
        default: 'http://localhost'
      WORDPRESS_THEME_NAME:
        description: 'WordPress folder theme name.'
        default: 'http://localhost:3000'

jobs:
  build_wp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-theme
        with:
          WORDPRESS_THEME_NAME: ${{ secrets.WORDPRESS_THEME_NAME }}

  start_wp:
    needs: build_wp
    steps:
      - name: Start WP
        shell: bash
        run: npm run start
        working-directory: ./wordpress

  build_next:
    needs: start_wp
    steps:
      - uses: ./.github/actions/build-frontend
        with:
          WORDPRESS_PATH: ${{ secrets.WORDPRESS_PATH }}
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}

  start_next:
    needs: build_next
    steps:
      - name: Start Next
        shell: bash
        run: npm run start
