name: Build and test solution
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build_start_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build-theme

      - name: Start WP
        shell: bash
        run: npm run start
        working-directory: ./wordpress

      - uses: ./.github/actions/build-frontend

      - name: Start Next is a thread
        shell: bash
        run: 'npm run start &'

      - name: TEST
        shell: bash
        run: |
          sleep 5
          curl http://localhost/wp-admin/post-new.php?post_type=wgg_preview&action=edit&wpGraphqlGutenbergServer=true
          curl http://localhost:3000/

      - name: Stop Next
        shell: bash
        run: killall npm
